### PR TITLE
fixes #1 email crash bug

### LINKED ISSUE #1: crashing on first email error
per TODO

### PR DESCRIPTION
**Pull request by matthewberryman**
@talltom wouldn't this be a way of handling that?
I'm a bit new at async/await, so please review

### CODE REVIEW

**Comment by matthewberryman** [comment]
noting I just added 5954136dad48feaf66fabfe427ac3ad73b3c359c

**Comment by talltom** [comment]
@matthewberryman - yes that would work. However, I wonder about using await inside the loop - I suspect it will make execution slow (if resolve is waiting from a callback request from the mail function the loop will stall)...although for this scheduler task this is no biggy as long as Lambda timeout is increased.

After some reading, it seems that something like this would be better (this is a good reference for me, as had this problem in the past so nice to find a good example):

```js
Promise.all([promises].map(p => p.catch(e => e)))
  .then(results => console.log(results)) // 1,Error: 2,3
  .catch(e => console.log(e));
```

What do you think? Also learning async/await at the moment.

Ref: https://stackoverflow.com/questions/31424561/wait-until-all-es6-promises-complete-even-rejected-promises

**Comment by matthewberryman** [comment]
@talltom I specifically marked the callback passed to forEach as async so each time forEach calls it it sets it up as async (within each one we independently await) to avoid the speed issue
https://github.com/MSFREACH/msf-reach-contacts-scheduler/blob/5954136dad48feaf66fabfe427ac3ad73b3c359c/src/functions/scheduler/index.js#L41

**Comment by matthewberryman** [comment]
Inspired by discussion at https://blog.lavrton.com/javascript-loops-how-to-handle-async-await-6252dd3c795

**Comment by talltom** [comment]
Noice!

**Pull request merged**
